project:
  type: book

book:
  title: "Advance data analytics course"
  author: "Andrés Pérez-Coronado"
  date: "08/02/2025"
  chapters:
    - index.qmd
    - 1.Issue for Decision-Making.qmd
    - 2.Key Players and Topics.qmd
    - 3.Collecting and Connecting Data.qmd
    - 4.Spotting Weak Predict Signals.qmd
    - 5.Data Storage and Traceability.qmd
    - 6.Interpreting Weak Predictive Signals.qmd    
    - 7.Planning and Taking Action.qmd
    - 8.Monitoring and Assessing Progress.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

